;;;

(defpackage :cl-proj
  (:use :cl)
  (:nicknames :pj)
  (:export 
   :+PJ-VERSION+
   :PJ-RELEASE
   :+RAD-TO-DEG+
   :+DEG-TO-RAD+
   :PJ-ERRNO
   :projUV
   :PJ-FWD
   :PJ-INV
   :PJ-TRANSFORM
   :PJ-DATUM-TRANSFORM
   :PJ-GEOCENTRIC-TO-GEODETIC
   :PJ-GEODETIC-TO-GEOCENTRIC
   :PJ-COMPARE-DATUMS
   :PJ-APPLY-GRIDSHIFT
   :PJ-DEALLOCATE-GRIDS
   :PJ-IS-LATLONG
   :PJ-IS-GEOCENT
   :PJ-PR-LIST
   :PJ-FREE
   :PJ-SET-FINDER
   :PJ-SET-SEARCHPATH
   :PJ-INIT
   :PJ-INIT-PLUS
   :PJ-GET-DEF
   :PJ-LATLONG-FROM-PROJ
   :PJ-MALLOC
   :PJ-DALLOC
   :PJ-STRERRNO
   :PJ-GET-ERRNO-REF
   :PJ-GET-RELEASE
   :PJ-ACQUIRE-LOCK
   :PJ-RELEASE-LOCK
   :PJ-CLEANUP-LOCK))


